<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Download App_Text__StyledText-sc-oo0k_e4aaf8</name>
   <tag></tag>
   <elementGuidId>f39bdfb3-f0a1-4dcc-bc7f-1279887ca1f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.Text__StyledText-sc-oo0kvp-0.gKkBjb.TextSearch__Input-sc-n7qqmw-2.DcYiA.search-input-elm.TextSearch__Input-sc-n7qqmw-2.DcYiA.search-input-elm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Try Saree, Kurti or Search by Product Code</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Text__StyledText-sc-oo0kvp-0 gKkBjb TextSearch__Input-sc-n7qqmw-2 DcYiA search-input-elm TextSearch__Input-sc-n7qqmw-2 DcYiA search-input-elm</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>greyBase</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-size</name>
      <type>Main</type>
      <value>16px</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-weight</name>
      <type>Main</type>
      <value>book</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;DesktopHeader__HeaderStyled-sc-r0p6o1-0 bOvSTC&quot;]/div[@class=&quot;sc-bdvvtL byHcNc&quot;]/div[@class=&quot;S_HeaderDesk-sc-w5uhst-0 dZnqtb header-container&quot;]/div[@class=&quot;S_DesktopSearch-sc-lmeel3-0 cDIjui search-component&quot;]/div[@class=&quot;TextSearch__S_SearchInput-sc-n7qqmw-0 zodAA&quot;]/input[@class=&quot;Text__StyledText-sc-oo0kvp-0 gKkBjb TextSearch__Input-sc-n7qqmw-2 DcYiA search-input-elm TextSearch__Input-sc-n7qqmw-2 DcYiA search-input-elm&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/div/div[2]/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
   </webElementXpaths>
</WebElementEntity>
